all: Q0 Q1 Q2 Q3 Q4 Q5

Q0: 
	gcc -g -Wall -std=c99 Q0.c -o q0

Q1:
	gcc -g -Wall -std=c99 Q1.c -o q1

Q2:
	gcc -g -Wall -std=c99 Q2.c -o q2

Q3:
	gcc -g -Wall -std=c99 Q3.c -o q3

Q4:
	gcc -g -Wall -std=c99 Q4.c -o q4

Q5:
	gcc -g -Wall -std=c99 Q5.c -o q5

clean:
	rm q0 q1 q2 q3 q4 q5
